site_name: DocuPage
site_url: https://cyphercrescent.github.io/docupage
nav:
  - Home: index.md
  - Documentations:
     - Docker:
       - DockerIntro.md
     - Wix:
       - WixDocs.md

repo_name: DocuPage 
repo_url: https://github.com/cyphercrescent/DocuPage

copyright: Copyright &copy; 2023 CypherCrescent

edit_uri: edit/main/docs/

plugins: 
  - search
  - social
  - tags

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/cyphercrescent/DocuPage
  generator: false
  tags:   
   Azure: azure
   Docker: docker
   Wix: wix
   HTML5: html5
   Linux: linux


  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences     

theme: 
  name: material
  favicon: img/Logo.png
  logo: img/InvertedLogo.png
  icon:
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      azure: fontawesome/brands/microsoft
      docker: fontawesome/brands/docker
      wix: fontawesome/brands/wix
      html5: fontawesome/brands/html5
      linux: fontawesome/brands/linux
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      edit: material/pencil 
      view: material/eye
    
  features:
    - navigation.footer
    - content.action.edit
    - content.action.view

  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


